#!/usr/bin/env python3
import jinja2
import os
import sys

from yaml import load, dump
try:
    from yaml import CLoader as Loader, CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper

def write_readme(packages):
    context = {
        "packages": [],
    }

    for package in packages:
        package_id = "com.github." + package.get("github", "").replace("/", ".")

        context["packages"].append({
            "github": package.get("github", ""),
            "id": package_id,
            "version": package.get("version", ""),
        })

    path = os.path.join("README.md")
    template_text = open("data/README.md.jinja2", "r").read()
    template = jinja2.Template(template_text)
    output = template.render(context) + "\n"

    with open(path, "w") as f:
        f.write(output)

def main():
    args = sys.argv[1:]

    stream = open("data/appcenter.yml", "r")
    data = load(stream, Loader=Loader)

    packages = []
    for package in data.get("packages", []):
        if len(args) == 0:
            packages.append(package)
        elif package.get("github", "") in args:
            packages.append(package)

    packages.sort(key=lambda x: x["github"])

    write_readme(packages)

if __name__ == "__main__":
    main()