name: com.github.arshubham.cipher

on:
  - push

jobs:
  com_github_arshubham_cipher:
    name: com.github.arshubham.cipher
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:elementary-juno
      options: --privileged
    steps:
    - name: Pull deb2flatpak ⬇️
      uses: actions/checkout@v2
    - name: Install Dependencies 📦
      run: |
        dnf install python3-pip
        pip3 install -r requirements.txt --user
    - name: Build Flatpak 🏗️
      run: ./scripts/appcenter arshubham/cipher
