name: com.github.dcharles525.crypt

on:
  - push

jobs:
  com_github_dcharles525_crypt:
    name: com.github.dcharles525.crypt
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:elementary-juno
      options: --privileged
    steps:
    - name: Pull deb2flatpak ⬇️
      uses: actions/checkout@v2
    - name: Install Dependencies 📦
      run: |
        dnf install python3-pip
        pip3 install -r requirements.txt --user
    - name: Build Flatpak 🏗️
      run: ./scripts/appcenter dcharles525/crypt
